version: "3.8"

services:
  nginx:
    image: bitnami/nginx:latest
    container_name: web-server-nginx
    restart: unless-stopped
    tty: true
    depends_on:
      - php-fpm
    ports:
     - '80:8080'
     - '443:8443'
    volumes:
     - ./nginx/myapp.conf:/opt/bitnami/nginx/conf/server_blocks/myapp.conf:ro
     - ../src/:/app
    networks:
      - bridge
  mysql:
    image:  bitnami/mysql:latest
    container_name: database_mysql
    tty: true
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=Chat
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password1234
    ports:
      - '3307:3306'
    volumes:
      - data_valumes:/bitnami/mysql/data
      - ./mysql/my_custom.cnf :/opt/bitnami/mysql/conf/my_custom.cnf:ro
    networks:
      - bridge

  php-fpm:
    image: bitnami/php-fpm:latest
    container_name: php_fpm
    volumes:
      - ../src/:/app/
    networks:
      - bridge
volumes:
  data_valumes:
    driver: local
networks:
  bridge:
    driver: bridge